robot: "trunk"
save_dir: "plots/"
file_format: "eps"

traj_dir: "sim_trajs/pac-man/" # figure8" # pac-man" # circle_z=-10" # 

show: {
    'ssmr': False,
    'ssmr_adiabatic_idw': False,
    'ssmr_adiabatic_modified_idw': True,
    'ssmr_adiabatic_qp': True,
    'ssmr_adiabatic_nn': False,
    'ssmr_adiabatic_linear': False,
    'ssmr_adiabatic_ct': False,
    'ssmr_origin': False,
    'tpwl': False,
    'koopman': False,
}
display_name: {
    'ssmr': "ASSMR (current model)",
    'ssmr_origin': "Origin",
    'ssmr_adiabatic_linear': "LB",
    'ssmr_adiabatic_ct': "CT",
    'ssmr_adiabatic_nn': "NN",
    'ssmr_adiabatic_qp': "QPR",
    'ssmr_adiabatic_idw': "IDW",
    'ssmr_adiabatic_modified_idw': "MIDW",
    'tpwl': "TPWL",
    'koopman': "Koopman",
}
color: {
    'ssmr': "tab:pink",
    'ssmr_origin': "tab:blue",
    'ssmr_adiabatic_linear': "tab:green",
    'ssmr_adiabatic_ct': "tab:blue",
    'ssmr_adiabatic_nn': "tab:brown",
    'ssmr_adiabatic_qp': "tab:purple",
    'ssmr_adiabatic_idw': "tab:red",
    'ssmr_adiabatic_modified_idw': "tab:red",
    'tpwl': 'tab:green',
    'koopman': 'tab:orange',
    'target': 'black'
}
linestyle: {
    'tpwl': '-',
    'koopman': '-',
    'target': '--'
}

markers: {
    'ssmr_origin': 's',
    'ssmr_adiabatic_linear': 'v',
    'ssmr_adiabatic_ct': '^',
    'ssmr_adiabatic_nn': 's',
    'ssmr_adiabatic_qp': 'o',
    'ssmr_adiabatic_idw': None,
    'ssmr_adiabatic_modified_idw': 'd',
    'tpwl': 'v',
    'koopman': '^',
    'target': None
}

linewidth: {
    'tpwl': 1,
    'koopman': 1,
    'target': 1,
    'ssmr_adiabatic_qp': 2,
    'ssmr_adiabatic_modified_idw': 2,
}

define_targets: {
    figure8: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 30, # 20, # 30, # 
        z_const: 0, # -10, # 0, # 
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    circle_z=-10: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 20,
        z_const: -10,
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    pac-man: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 20,
        z_const: -10,
        t_in_pacman: 1.,
        t_out_pacman: 1.,
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    }
}

plot_mpc_rollouts: False


# TODO
##############################################
# Problem 2, Circle on side
##############################################
# M = 3
# T = 5
# N = 1000
# t_target = np.linspace(0, M*T, M*N)
# th = np.linspace(0, M*2*np.pi, M*N)
#
# r = 15
# phi = 17
# x_target = np.zeros(M*N)
# y_target = r * np.sin(phi * T / (2 * np.pi) * th)
# z_target = r - r * np.cos(phi * T / (2 * np.pi) * th) + 107.0
