# collect decay data
# run "./launch_sofa_collectDecayTrajectories.py"
collectDecayData: {
  robot: "trunk",
  u_dim: 8,
  # must specify one save_dir per pre_tensioning and in matching order!
  save_dir: [
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/origin/decay",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/north/decay",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/west/decay",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/south/decay",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/east/decay"
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/northwest/decay",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/southwest/decay",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/southeast/decay",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/northeast/decay",
  ],
  u_min: 0,
  u_max: 1000,
  pre_tensioning: [
    # [0, 0, 0, 0, 0, 0, 0, 0],
    # [200, 0, 0, 0, 200, 0, 0, 0],
    # [0, 200, 0, 0, 0, 200, 0, 0],
    # [0, 0, 200, 0, 0, 0, 200, 0],
    # [0, 0, 0, 200, 0, 0, 0, 200]
    [200, 200, 0, 0, 200, 200, 0, 0],
    [0, 200, 200, 0, 0, 200, 200, 0],
    [0, 0, 200, 200, 0, 0, 200, 200],
    [200, 0, 0, 200, 200, 0, 0, 200],
  ],
  combine_inputs: [0, 800],
  n_traj: 40
}

# collect open-loop controlled data
# run "./launch_sofa_collectInputTrajectories.py"
collectInputData: {
  robot: "trunk",
  u_dim: 8,
  u_max: 100,
  save_dir: [
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/origin/open-loop",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/north/open-loop",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/west/open-loop",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/south/open-loop",
    # "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/east/open-loop"
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/northwest/open-loop",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/southwest/open-loop",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/southeast/open-loop",
    "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/northeast/open-loop",
  ],
  pre_tensioning: [
    # [0, 0, 0, 0, 0, 0, 0, 0],
    # [200, 0, 0, 0, 200, 0, 0, 0],
    # [0, 200, 0, 0, 0, 200, 0, 0],
    # [0, 0, 200, 0, 0, 0, 200, 0],
    # [0, 0, 0, 200, 0, 0, 0, 200]
    [200, 200, 0, 0, 200, 200, 0, 0],
    [0, 200, 200, 0, 0, 200, 200, 0],
    [0, 0, 200, 200, 0, 0, 200, 200],
    [200, 0, 0, 200, 200, 0, 0, 200],
  ],
  # spline_lhs: False,
  # n_samples: 100
  # n_interp_points: 20
}