robot: "trunk" #trunk, hardware
save_dir: "plots/"
file_format: "png"

#traj_dir: "sim_trajs/circle_z=-10" # figure8" #
traj_dir: ""

show: {
    'ssmr_delays': False, # Full obsevables
    'ssmr_posvel': False, # pos-vel
    'ssmr_singleDelay': False, # Single delay embedding
    'ssmr_linear': False, # Linear model
    # Adiabatic SSM settings
    'ssmr_adiabatic_idw': False,
    'ssmr_adiabatic_modified_idw': False,
    'ssmr_adiabatic_qp': False,
    'ssmr_adiabatic_nn': False,
    'ssmr_adiabatic_linear': False,
    'ssmr_adiabatic_ct': False,
    'tpwl': False,
    'koopman': True,
    'DMD': False,
    'rompc': False
}
display_name: {
    'ssmr_delays': "SSMR\n(4 Delays)",
    'ssmr_posvel': "SSMR\n(Pos-Vel)", # "SSMR (origin)",
    'ssmr_singleDelay': "SSMR\n(1 Delay)", # Single delay embedding
    'ssmr_linear': "SSSR\n(1 Delay)", # Linear SSMR Model
    'ssmr_adiabatic_linear': "LB",
    'ssmr_adiabatic_ct': "CT",
    'ssmr_adiabatic_nn': "NN",
    'ssmr_adiabatic_qp': "QPR",
    'ssmr_adiabatic_idw': "IDW",
    'ssmr_adiabatic_modified_idw': "MIDW",
    'tpwl': "TPWL",
    'koopman': "EDMD",
    'DMD': "DMD",
    'rompc': "ROMPC",
}

legend_name: {
    'ssmr_delays': "SSMR (4 Delays)",
    'ssmr_posvel': "SSMR (Pos-Vel)", # "SSMR (origin)",
    'ssmr_singleDelay': "SSMR (1 Delay)", # Single delay embedding
    'ssmr_linear': "SSSR (1 Delay)", # Linear SSMR Model
    'ssmr_adiabatic_linear': "tab:green",
    'ssmr_adiabatic_ct': "tab:blue",
    'ssmr_adiabatic_nn': "tab:brown",
    'ssmr_adiabatic_qp': "tab:purple",
    'ssmr_adiabatic_idw': "tab:red",
    'ssmr_adiabatic_modified_idw': "tab:red",
    'tpwl': "TPWL",
    'koopman': "EDMD",
    'DMD': "DMD",
    'rompc': "ROMPC",
}


color: {
    'ssmr_delays': 'tab:blue',
    'ssmr_posvel': 'tab:red',
    'ssmr_singleDelay': 'tab:orange',
    'ssmr_linear': 'tab:purple',
    'ssmr_adiabatic_linear': "tab:green",
    'ssmr_adiabatic_ct': "tab:blue",
    'ssmr_adiabatic_nn': "tab:brown",
    'ssmr_adiabatic_qp': "tab:purple",
    'ssmr_adiabatic_idw': "tab:red",
    'ssmr_adiabatic_modified_idw': "tab:red",
    'tpwl': 'tab:olive',
    'koopman': 'tab:green',
    'DMD': "tab:cyan",
    'rompc': 'tab:purple',
    'target': 'black'
}
linestyle: {
    'ssmr_delays': '-',
    'ssmr_posvel': '-',
    'ssmr_singleDelay': '-',
    'ssmr_linear': '-',
    'ssmr_adiabatic_linear': '-',
    'ssmr_adiabatic_ct': '-',
    'ssmr_adiabatic_nn': '-',
    'ssmr_adiabatic_qp': '-',
    'ssmr_adiabatic_idw': '-',
    'ssmr_adiabatic_modified_idw': '-',
    'tpwl': '-',
    'koopman': '-',
    'DMD': '-',
    'rompc': '-',
    'target': '--'
}

altlinestyle: {
    'ssmr_delays': '-o',
    'ssmr_posvel': '-*',
    'ssmr_singleDelay': '-D',
    'ssmr_linear': '-^',
    'ssmr_nnssm': '-',
    'ssmr_ctssm': '-',
    'ssmr_assm_qp2d_n=100': '-',
    'ssmr_assm_idw3d_n=100': '-',
    'ssmr_assm_ridge2d_n=100': '-',
    'ssmr_linssm': '-',
    'tpwl': '-+',
    'koopman': '-|',
    'DMD': '-s',
    'rompc': '-',
    'target': '--'
}

linewidth: {
    'ssmr_delays': 2,
    'ssmr_posvel': 2,
    'ssmr_singleDelay': 3,
    'ssmr_linear': 2,
    'ssmr_adiabatic_linear': 2,
    'ssmr_adiabatic_ct': 2,
    'ssmr_adiabatic_nn': 2,
    'ssmr_adiabatic_qp': 2,
    'ssmr_adiabatic_idw': 2,
    'ssmr_adiabatic_modified_idw': 2,
    'tpwl': 2,
    'koopman': 2,
    'DMD': 2,
    'rompc': 2,
    'target': 1
}

alpha: {
    'ssmr_delays': 0.7,
    'ssmr_posvel': 0.7,
    'ssmr_singleDelay': 0.7,
    'ssmr_linear': 1,
    'tpwl': 0.7,
    'koopman': 0.7,
    'DMD': 0.5,
    'rompc': 1,
    'target': 1.5
}

select_target: "pacman"
# select_target: "figure8"
# Figure8 target
define_targets: {
    figure8: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 30, # 20, # 30, # 
        z_const: 0, # -10, # 0, # 
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    circle: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 20,
        z_const: -10,
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    pacman: {
        z_const: -10, # -10, # 0, # 
        z_lb: null,
        z_ub: null,
        T: 10,
        M: 1,
        N: 1000,
        radius: 20,
        t_in_pacman: 1., 
        t_out_pacman: 1.,
    },
    custom: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    ASL: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    stanford: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    star: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    }
}

plot_mpc_rollouts: False


# TODO
##############################################
# Problem 2, Circle on side
##############################################
# M = 3
# T = 5
# N = 1000
# t_target = np.linspace(0, M*T, M*N)
# th = np.linspace(0, M*2*np.pi, M*N)
#
# r = 15
# phi = 17
# x_target = np.zeros(M*N)
# y_target = r * np.sin(phi * T / (2 * np.pi) * th)
# z_target = r - r * np.cos(phi * T / (2 * np.pi) * th) + 107.0

# NAME = 'circle'