robot: "trunk"
save_dir: "plots/"
file_format: "png"

traj_dir: "sim_trajs/figure8_z=-20"

show: {
    'ssmr': False,
    'ssmr_origin': True,
    'ssmr_nnssm': False,
    'ssmr_ctssm': True,
    'ssmr_linssm': False,
    'tpwl': False,
    'koopman': False,
    'rompc': False
}
display_name: {
    'ssmr': "ASSMR (current model)",
    'ssmr_origin': "SSMR (origin)",
    'ssmr_nnssm': "ASSMR (NN, n=9)",
    'ssmr_ctssm': "ASSMR (CT, n=9)",
    'ssmr_linssm': "ASSMR (linear, n=9)",
    'tpwl': "TPWL",
    'koopman': "Koopman",
    'rompc': "ROMPC",
}
color: {
    'ssmr': 'tab:green',
    'ssmr_origin': 'tab:blue',
    'ssmr_nnssm': 'tab:red',
    'ssmr_ctssm': 'tab:orange',
    'ssmr_linssm': 'tab:purple',
    'tpwl': 'tab:red',
    'koopman': 'tab:green',
    'rompc': 'tab:purple',
    'target': 'black'
}
linestyle: {
    'ssmr': '-',
    'ssmr_origin': '-',
    'ssmr_nnssm': '-',
    'ssmr_ctssm': '-',
    'ssmr_linssm': '-',
    'tpwl': '-',
    'koopman': '-',
    'rompc': '-',
    'target': '--'
}
linewidth: {
    'ssmr': 2,
    'ssmr_origin': 2,
    'ssmr_nnssm': 2,
    'ssmr_ctssm': 2,
    'ssmr_linssm': 2,
    'tpwl': 2,
    'koopman': 2,
    'rompc': 2,
    'target': 1
}

select_target: "figure8"
# Figure8 target
define_targets: {
    figure8: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 25, # 30, # 
        z_const: -20, # 0, # 
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    circle: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 20,
        z_const: -20,
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    }
}

plot_mpc_rollouts: False


# TODO
##############################################
# Problem 2, Circle on side
##############################################
# M = 3
# T = 5
# N = 1000
# t_target = np.linspace(0, M*T, M*N)
# th = np.linspace(0, M*2*np.pi, M*N)
#
# r = 15
# phi = 17
# x_target = np.zeros(M*N)
# y_target = r * np.sin(phi * T / (2 * np.pi) * th)
# z_target = r - r * np.cos(phi * T / (2 * np.pi) * th) + 107.0

# NAME = 'circle'