robot: "hardware" #trunk, hardware
save_dir: "plots/"
file_format: "png"

#traj_dir: "sim_trajs/circle_z=-10" # figure8" #
traj_dir: ""

show: {
    'ssmr_delays': False, # Full obsevables
    'ssmr_posvel': False, # pos-vel
    'ssmr_singleDelay': False, # Single delay embedding
    'ssmr_linear': True, # Linear model
    'ssmr_linear_LDO': True, # LDO model
    # Adiabatic SSM settings
    'ssmr_nnssm': False,
    'ssmr_ctssm': False,
    'ssmr_linssm': False,
    'ssmr_assm_qp2d_n=100': False,
    'ssmr_assm_idw3d_n=100': False,
    'ssmr_assm_ridge2d_n=100': False,
    'tpwl': False,
    'koopman': False,
    'DMD': False,
    'rompc': False
}
display_name: {
    'ssmr_delays': "SSMR\n(4 Delays)",
    'ssmr_posvel': "SSMR\n(Pos-Vel)", # "SSMR (origin)",
    'ssmr_singleDelay': "SSMR\n(1 Delay)", # Single delay embedding
    'ssmr_linear': "Linear SSMR", # Linear SSMR Model
    'ssmr_linear_LDO': "Linear SSMR (w/ LDO)", # Linear SSMR Model + LDO
    'ssmr_nnssm': "ASSMR (NN, N=9)",
    'ssmr_ctssm': "CT-2D (N=9)", # "ASSMR (CT, N=9)",
    'ssmr_assm_qp2d_n=100': "QP-2D (N=100)", # "ASSMR (QP-2D, N=100)",
    'ssmr_assm_idw3d_n=100': "IDW-3D (N=100)", # 'ASSMR (IDW-3D, N=100)',
    'ssmr_assm_ridge2d_n=100': 'ASSMR (Ridge regression, N=100, degree=3)',
    'ssmr_linssm': "ASSMR (linear, n=9)",
    'tpwl': "TPWL",
    'koopman': "EDMD",
    'DMD': "DMD",
    'rompc': "ROMPC",
}

legend_name: {
    'ssmr_delays': "SSMR (4 Delays)",
    'ssmr_posvel': "SSMR (Pos-Vel)", # "SSMR (origin)",
    'ssmr_singleDelay': "SSMR (1 Delay)", # Single delay embedding
    'ssmr_linear': "Linear SSMR", # Linear SSMR Model
    'ssmr_linear_LDO': "Linear SSMR (w/ LDO)", # Linear SSMR Model + LDO
    'ssmr_nnssm': "ASSMR (NN, N=9)",
    'ssmr_ctssm': "CT-2D (N=9)", # "ASSMR (CT, N=9)",
    'ssmr_assm_qp2d_n=100': "QP-2D (N=100)", # "ASSMR (QP-2D, N=100)",
    'ssmr_assm_idw3d_n=100': "IDW-3D (N=100)", # 'ASSMR (IDW-3D, N=100)',
    'ssmr_assm_ridge2d_n=100': 'ASSMR (Ridge regression, N=100, degree=3)',
    'ssmr_linssm': "ASSMR (linear, n=9)",
    'tpwl': "TPWL",
    'koopman': "EDMD",
    'DMD': "DMD",
    'rompc': "ROMPC",
}


color: {
    'ssmr_delays': 'tab:blue',
    'ssmr_posvel': 'tab:red',
    'ssmr_singleDelay': 'tab:orange',
    'ssmr_linear': 'tab:purple',
    'ssmr_linear_LDO': "tab:green", # Linear SSMR Model + LDO
    'ssmr_nnssm': 'tab:red',
    'ssmr_ctssm': 'tab:orange',
    'ssmr_assm_qp2d_n=100': 'tab:purple',
    'ssmr_assm_idw3d_n=100': 'tab:green',
    'ssmr_assm_ridge2d_n=100': 'tab:red',
    'ssmr_linssm': 'tab:purple',
    'tpwl': 'tab:olive',
    'koopman': 'tab:green',
    'DMD': "tab:cyan",
    'rompc': 'tab:purple',
    'target': 'black'
}
linestyle: {
    'ssmr_delays': '-',
    'ssmr_posvel': '-',
    'ssmr_singleDelay': '-',
    'ssmr_linear': '-',
    'ssmr_linear_LDO': '-', # Linear SSMR Model + LDO
    'ssmr_nnssm': '-',
    'ssmr_ctssm': '-',
    'ssmr_assm_qp2d_n=100': '-',
    'ssmr_assm_idw3d_n=100': '-',
    'ssmr_assm_ridge2d_n=100': '-',
    'ssmr_linssm': '-',
    'tpwl': '-',
    'koopman': '-',
    'DMD': '-',
    'rompc': '-',
    'target': '--'
}

altlinestyle: {
    'ssmr_delays': '-o',
    'ssmr_posvel': '-*',
    'ssmr_singleDelay': '-D',
    'ssmr_linear': '-^',
    'ssmr_nnssm': '-',
    'ssmr_ctssm': '-',
    'ssmr_assm_qp2d_n=100': '-',
    'ssmr_assm_idw3d_n=100': '-',
    'ssmr_assm_ridge2d_n=100': '-',
    'ssmr_linssm': '-',
    'tpwl': '-+',
    'koopman': '-|',
    'DMD': '-s',
    'rompc': '-',
    'target': '--'
}

linewidth: {
    'ssmr_delays': 2,
    'ssmr_posvel': 2,
    'ssmr_singleDelay': 3,
    'ssmr_linear': 2,
    'ssmr_linear_LDO': 2, # Linear SSMR Model + LDO
    'ssmr_nnssm': 2,
    'ssmr_ctssm': 2,
    'ssmr_assm_qp2d_n=100': 2,
    'ssmr_assm_idw3d_n=100': 2,
    'ssmr_assm_ridge2d_n=100': 2,
    'ssmr_linssm': 2,
    'tpwl': 2,
    'koopman': 2,
    'DMD': 2,
    'rompc': 2,
    'target': 2
}

alpha: {
    'ssmr_delays': 0.7,
    'ssmr_posvel': 0.7,
    'ssmr_singleDelay': 0.7,
    'ssmr_linear': 0.1,
    'ssmr_linear_LDO': 0.5, # Linear SSMR Model + LDO
    'tpwl': 0.7,
    'koopman': 0.7,
    'DMD': 0.5,
    'rompc': 1,
    'target': 1.5
}

# select_target: "circle"
select_target: "figure8"
# Figure8 target
define_targets: {
    figure8: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 30, # 20, # 30, # 
        z_const: 0, # -10, # 0, # 
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    circle: {
        M: 1,
        T: 10,
        N: 1000,
        radius: 20,
        z_const: -10,
        # state constraints
        z_lb: null, # [-16, -16],
        z_ub: null  # [16, 5]
    },
    pacman: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    custom: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    ASL: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    stanford: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    },
    star: {
        z_const: 0, # -10, # 0, # 
        z_lb: null,
        z_ub: null
    }
}

plot_mpc_rollouts: False


# TODO
##############################################
# Problem 2, Circle on side
##############################################
# M = 3
# T = 5
# N = 1000
# t_target = np.linspace(0, M*T, M*N)
# th = np.linspace(0, M*2*np.pi, M*N)
#
# r = 15
# phi = 17
# x_target = np.zeros(M*N)
# y_target = r * np.sin(phi * T / (2 * np.pi) * th)
# z_target = r - r * np.cos(phi * T / (2 * np.pi) * th) + 107.0

# NAME = 'circle'