import numpy as np

def diamond_softrobot_Bmat_O3(in1):
    #diamond_softrobot_Bmat_O3
    #    B_mat = diamond_softrobot_Bmat_O3(IN1)
    
    #    This function was generated by the Symbolic Math Toolbox version 9.0.
    #    09-Jun-2022 09:53:22
    
    mt1 = np.array([0.0,0.0,0.0,-6.438668309935568e-2,-8.020081222603158e-2,1.647850231855044e-2,0.0,0.0,0.0,-8.596353237564298e-2,5.007862554292317e-2])
    mt2 = np.array([3.402583494640329e-2,0.0,0.0,0.0,-8.844126815338683e-3,7.261452954276311e-2,-5.262805850636806e-2,0.0,0.0,0.0,-7.52561091863776e-3])
    mt3 = np.array([-3.80219384164585e-2,-9.688298583928201e-2])
    B_mat = np.reshape(np.hstack([mt1,mt2,mt3]), (4, 6)).T
    return B_mat
