RDType: flow
ROMOrder: 3
SSMDim: 6
SSMOrder: 3
custom_delay: 1
data_dir: /home/jalora/Desktop/diamond
data_subdirs: []
decay_dir: decay/
decay_test_set:
- 0
- 4
dt: 0.01
input_dim: 4
input_test_data_dir:
- open-loop_circle
input_train_data_dir: open-loop
input_train_ratio: 0.8
model_save_dir: SSMmodelsPy/
n_delay: 4
n_nodes: 1628
oDOF: 3
observables: delay-embedding
poly_u_order: 1
rDOF: 3
reduced_coordinates: local
rest_file: rest_qv.pkl
ridge_alpha:
  B: 0
  manifold: 0.0
  reduced_dynamics: 0.0
robot_dir: /home/jalora/soft-robot-control/examples/hardware
subsample: 1
t_decay:
- 1
- 4
t_truncate:
- 0.2
- 2.6
tip_node: 1354
use_ssmlearn: py
